package VIEW;

public enum TipoJanela {
    MENU_PRINCIPAL,
    MENU_LISTAR_PRODUTOS,
    LISTAR_PRODUTOS,
    CADASTRAR_PRODUTOS,
    EXCLUIR_PRODUTOS,
    ATUALIZAR_PRODUTOS,
    BUSCAR_PRODUTO,
    REGISTRAR_USUARIO,
    LOGIN_USUARIO;

}
